version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: postgres_db
    volumes:
      - .db:/var/lib/posrgresql/data
      # - ./initdb:/docker-entrypoint-initdb.d

# volumes:
#   db_data: {}
